language: node_js
node_js:
  - 10

os:
  - osx

before_install:
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- --default-toolchain=1.38.0 --profile=minimal -y
  - export PATH=${TRAVIS_HOME}/.cargo/bin:$PATH
  - rustup override set nightly-2019-07-10
  - rustc --version
  - rustup --version
  - cargo --version

after_success: npm run report && npm run coveralls

before_deploy:
  # Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
  - |
    function npm_dist_tag() {
      if [[ "$TRAVIS_TAG" = *"-"* ]]; then
        echo "next"
      else
        echo "latest"
      fi
    }

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    tag: $(npm_dist_tag)
    on:
      tags: true
      repo: dolcalmi/stellar-thresh-sig-js
      node: 10

script:
  - npm run clean
  - npm explore @kzen-networks/thresh-sig -- npm run build
  - npm test
